# Generated by Django 5.0.4 on 2024-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_user_type_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('TR', 'Trainer'), ('CL', 'Client')], default='CL', editable=False),
        ),
    ]
