# Generated by Django 5.0.4 on 2024-05-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_person_client_trainer_person_check_trainee_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
