# Generated by Django 5.0.4 on 2024-05-12 05:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_client_height_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[core.models.validate_weight]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[core.models.validate_height]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[core.models.validate_weight]),
        ),
    ]
