# Generated by Django 5.0.4 on 2024-05-12 05:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_client_weight_alter_trainer_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[core.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[core.models.phone_number_validator]),
        ),
    ]
