# Generated by Django 5.0.4 on 2024-04-30 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='base/videos')),
            ],
        ),
        migrations.CreateModel(
            name='MainAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, null=True)),
                ('weeks', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/images')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rel', to='base.day')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_rel', to='base.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.ManyToManyField(through='base.Plan_Day', to='base.day'),
        ),
        migrations.CreateModel(
            name='Plan_Day_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_rel', to='base.exercise')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_day_rel', to='base.plan_day')),
            ],
            options={
                'unique_together': {('plan_day', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='plan_day',
            name='exercise',
            field=models.ManyToManyField(through='base.Plan_Day_Exercise', to='base.exercise'),
        ),
        migrations.CreateModel(
            name='SubAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_advice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_advices', to='base.mainadvice')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('health_conditions', models.TextField(blank=True)),
                ('fitness_goals', models.TextField(blank=True)),
                ('sessions_completed', models.PositiveIntegerField(blank=True, default=0)),
                ('progress_notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingFocus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField(default=1, help_text='The difficulty level of the plan type.')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='base/images')),
                ('muscle', models.ManyToManyField(to='base.muscle')),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='training_focus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trainingfocus'),
        ),
        migrations.AlterUniqueTogether(
            name='plan_day',
            unique_together={('plan', 'day')},
        ),
    ]
