# Generated by Django 5.0.4 on 2024-04-09 15:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(default='https://www.bing.com/images/search?view=detailV2&ccid=S1oOtfns&id=2A6FA1A8387A12EB17BD4AB7D2C4549D93302822&thid=OIP.S1oOtfns4P4JKMgbKVUUZwAAAA&mediaurl=https%3A%2F%2Fwww.ncenet.com%2Fwp-content%2Fuploads%2F2020%2F04%2FNo-image-found.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.4b5a0eb5f9ece0fe0928c81b29551467%3Frik%3DIigwk51UxNK3Sg%26pid%3DImgRaw%26r%3D0&exph=275&expw=275&q=image+not+found&simid=608049142248450475&FORM=IRPRST&ck=9097C7B3F88BAE6EF1FADA5521B7095A&selectedIndex=7&itb=0&ajaxhist=0&ajaxserp=0', validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.SmallIntegerField()),
                ('reps', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.day')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='exercise',
            field=models.ManyToManyField(through='base.ExerciseDay', to='base.exercise'),
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField(default=1, help_text='The difficulty level of the plan type.')),
                ('description', models.TextField()),
                ('image', models.URLField(default='https://www.bing.com/images/search?view=detailV2&ccid=S1oOtfns&id=2A6FA1A8387A12EB17BD4AB7D2C4549D93302822&thid=OIP.S1oOtfns4P4JKMgbKVUUZwAAAA&mediaurl=https%3A%2F%2Fwww.ncenet.com%2Fwp-content%2Fuploads%2F2020%2F04%2FNo-image-found.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.4b5a0eb5f9ece0fe0928c81b29551467%3Frik%3DIigwk51UxNK3Sg%26pid%3DImgRaw%26r%3D0&exph=275&expw=275&q=image+not+found&simid=608049142248450475&FORM=IRPRST&ck=9097C7B3F88BAE6EF1FADA5521B7095A&selectedIndex=7&itb=0&ajaxhist=0&ajaxserp=0', validators=[django.core.validators.URLValidator()])),
                ('muscle', models.ManyToManyField(to='base.muscle')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('advice', models.TextField(blank=True, null=True)),
                ('weeks', models.SmallIntegerField()),
                ('day', models.ManyToManyField(to='base.day')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.plantype')),
            ],
        ),
    ]
