# Generated by Django 5.0.4 on 2024-05-08 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='trainee',
            constraint=models.CheckConstraint(check=models.Q(('gender', 'M'), ('gender', 'F'), _connector='OR'), name='Check_Gender'),
        ),
    ]
