# Generated by Django 5.0.4 on 2024-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exerciseday',
            name='reps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
