# Generated by Django 5.0.4 on 2024-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_trainee_gender_trainee_check_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='fitness_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='health_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='sessions_completed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
