# Generated by Django 5.0.4 on 2024-04-09 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_day_name_alter_exerciseday_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscle',
            name='image',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='plantype',
            name='image',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
