# Generated by Django 5.0.4 on 2024-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_trainee_fitness_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
    ]
