# Generated by Django 5.0.4 on 2024-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_muscle_image_alter_plantype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
