# Generated by Django 5.0.4 on 2024-05-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_trainer_rename_trainee_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
