# Generated by Django 5.0.4 on 2024-04-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='exercise',
            field=models.ManyToManyField(related_name='exercise_day', through='base.ExerciseDay', to='base.exercise'),
        ),
    ]
