# Generated by Django 5.0.4 on 2024-04-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_exerciseday_plan_alter_exerciseday_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='day',
        ),
    ]
