# Generated by Django 5.0.4 on 2024-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_plan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.ManyToManyField(related_name='planday', to='base.day'),
        ),
    ]
