# Generated by Django 5.0.4 on 2024-04-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_plan_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='base.plan'),
        ),
    ]
