# Generated by Django 5.0.4 on 2024-04-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_exerciseday_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseday',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='base.day'),
        ),
        migrations.AlterField(
            model_name='exerciseday',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='base.exercise'),
        ),
    ]
