# Generated by Django 5.0.4 on 2024-04-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_exerciseday_day_alter_exerciseday_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.plan'),
        ),
    ]
