# Generated by Django 5.0.4 on 2024-04-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_plan_day_plan_day_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.ManyToManyField(through='base.Plan_Day', to='base.day'),
        ),
        migrations.AddField(
            model_name='plan_day',
            name='exercise',
            field=models.ManyToManyField(through='base.Plan_Day_Exercise', to='base.exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='plan_day',
            unique_together={('plan', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='plan_day_exercise',
            unique_together={('plan_day', 'exercise')},
        ),
    ]
