# Generated by Django 5.0.4 on 2024-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_plan_day_plan_day_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_day_exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='plan_day_exercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
