# Generated by Django 5.0.4 on 2024-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_plan_day_exercise_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(max_length=255),
        ),
    ]
