# Generated by Django 5.0.4 on 2024-04-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_exercise_reps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanType',
            new_name='TrainingFocus',
        ),
    ]
