# Generated by Django 5.0.4 on 2024-04-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_trainingfocus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingfocus',
            name='image',
        ),
        migrations.CreateModel(
            name='TrainingFocusImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='base/images')),
                ('TrainingFocus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trainingfocus')),
            ],
        ),
    ]
