# Generated by Django 5.0.4 on 2024-04-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_trainingfocus_image_trainingfocusimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingFocusImages',
        ),
    ]
