# Generated by Django 5.0.4 on 2024-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_delete_trainingfocusimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='base/videos'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images'),
        ),
        migrations.AddField(
            model_name='trainingfocus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images'),
        ),
    ]
