# Generated by Django 5.0.4 on 2024-04-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_exercise_image_exercise_video_plan_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadvice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images'),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='base/images'),
        ),
    ]
