# Generated by Django 5.0.4 on 2024-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_mainadvice_image_alter_muscle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='age',
        ),
        migrations.AddField(
            model_name='trainee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
