# Generated by Django 5.0.4 on 2024-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_trainee_age_trainee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
